include: package:lints/recommended.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_unused_constructor_parameters: true
    unnecessary_null_in_if_null_operators: true
    no_duplicate_case_values: true
    prefer_is_empty: true
    always_specify_types: true
    avoid_single_cascade_in_expression_statements: true