name: rest_countries_data
description: "A Dart package that acts as a wrapper for the REST Countries API, providing easy access to countries data."
version: 1.0.1
repository: https://github.com/Frankdroid7/rest_countries_package

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.4.0

dev_dependencies:
  mocktail: ^1.0.4
  lints: ^5.0.0
  test: ^1.25.15
